# Generated by Django 5.2.5 on 2026-02-18 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoggedOutSpec",
            fields=[
                (
                    "spec_path",
                    models.CharField(max_length=64, verbose_name="spec_path"),
                ),
                (
                    "slug",
                    models.SlugField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Logged out specs",
            },
        ),
    ]
