BBBBBBB BBBBBBBBBBB
BBBB BBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXXX
XXXX XXXXXXXXXXXXXXXXX
  XXXFFFFFFFFXXXX
XXXXXX
XXXX XXXXXXXXXXXXXXXXX
  XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX X XXXXXXXXXXXXX
    XXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
      BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBB BBB BBBBBBBBBBBBBBBB BBBBBBBBBBBB
      BB BBBBBBBBBBBBB
      XXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        BBBBBBBBBBBBBBBBBBBBBBB B BBB BBBBBBBBBBBBBBBB BBBBBBBBBBBB
      XXXXX
      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXXX
      XXXXXX
      BBBB
      XX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXX XXXXXXXX
      BBBBB
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB
