# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _

LANG_CHOICES = (
    ("aa", _(u"Afar")),
    ("ab", _(u"Abkhazian")),
    ("af", _(u"Afrikaans")),
    ("ak", _(u"Akan")),
    ("sq", _(u"Albanian")),
    ("am", _(u"Amharic")),
    ("ar", _(u"Arabic")),
    ("an", _(u"Aragonese")),
    ("hy", _(u"Armenian")),
    ("as", _(u"Assamese")),
    ("av", _(u"Avaric")),
    ("ae", _(u"Avestan")),
    ("ay", _(u"Aymara")),
    ("az", _(u"Azeri")),
    ("ba", _(u"Bashkir")),
    ("bm", _(u"Bambara")),
    ("eu", _(u"Basque")),
    ("be", _(u"Belarusian")),
    ("bn", _(u"Bengali")),
    ("bh", _(u"Bihari")),
    ("bi", _(u"Bislama")),
    ("bo", _(u"Tibetan")),
    ("bs", _(u"Bosnian")),
    ("br", _(u"Breton")),
    ("bg", _(u"Bulgarian")),
    ("my", _(u"Burmese")),
#    ("ca", _(u"Catalan; Valencian")),
    ("ca", _(u"Catalan")),
    ("cs", _(u"Czech")),
    ("ch", _(u"Chamorro")),
    ("ce", _(u"Chechen")),
    ("zh", _(u"Chinese")),
    ("cv", _(u"Chuvash")),
    ("kw", _(u"Cornish")),
    ("co", _(u"Corsican")),
    ("cr", _(u"Cree")),
    ("cy", _(u"Welsh")),
    ("da", _(u"Danish")),
    ("de", _(u"German")),
#    ("dv", _(u"Divehi; Maldivian")),
    ("dv", _(u"Divehi")),
#    ("nl", _(u"Dutch; Flemish")),
    ("nl", _(u"Dutch")),
    ("dz", _(u"Dzongkha")),
    ("el", _(u"Greek")),
    ("en", _(u"English")),
    ("eo", _(u"Esperanto")),
    ("et", _(u"Estonian")),
    ("ee", _(u"Ewe")),
    ("fo", _(u"Faroese")),
    ("fa", _(u"Persian")),
    ("fj", _(u"Fijian")),
    ("fi", _(u"Finnish")),
    ("fr", _(u"French")),
    ("fy", _(u"Western Frisian")),
    ("ff", _(u"Fulah")),
    ("ka", _(u"Georgian")),
    ("gd", _(u"Gaelic")),
    ("ga", _(u"Irish")),
    ("gl", _(u"Galician")),
    ("gv", _(u"Manx")),
    ("gn", _(u"Guarani")),
    ("gu", _(u"Gujarati")),
    ("ht", _(u"Haitian")),
    ("ha", _(u"Hausa")),
    ("he", _(u"Hebrew")),
    ("hz", _(u"Herero")),
    ("hi", _(u"Hindi")),
    ("ho", _(u"Hiri Motu")),
    ("hr", _(u"Croatian")),
    ("hu", _(u"Hungarian")),
    ("ig", _(u"Igbo")),
    ("is", _(u"Icelandic")),
    ("io", _(u"Ido")),
#    ("ii", _(u"Sichuan-Yi; Nuosu")),
    ("ii", _(u"Sichuan-Yi")),
    ("iu", _(u"Inuktitut")),
    ("id", _(u"Indonesian")),
    ("ik", _(u"Inupiaq")),
    ("it", _(u"Italian")),
    ("jv", _(u"Javanese")),
    ("ja", _(u"Japanese")),
    ("kl", _(u"Kalaallisut")),
    ("kn", _(u"Kannada")),
    ("ks", _(u"Kashmiri")),
    ("kr", _(u"Kanuri")),
    ("kk", _(u"Kazakh")),
    ("km", _(u"Khmer")),
#    ("ki", _(u"Kikuyu; Gikuyu")),
    ("ki", _(u"Kikuyu")),
    ("rw", _(u"Kinyarwanda")),
#    ("ky", _(u"Kirghiz; Kyrgyz")),
    ("ky", _(u"Kirghiz")),
    ("kv", _(u"Komi")),
    ("kg", _(u"Kongo")),
    ("ko", _(u"Korean")),
#    ("kj", _(u"Kuanyama; Kwanyama")),
    ("kj", _(u"Kuanyama")),
    ("ku", _(u"Kurdish")),
    ("lo", _(u"Lao")),
    ("la", _(u"Latin")),
    ("lv", _(u"Latvian")),
    ("li", _(u"Limburgish")),
    ("ln", _(u"Lingala")),
    ("lt", _(u"Lithuanian")),
    ("lb", _(u"Luxembourgish")),
    ("lu", _(u"Luba-Katanga")),
    ("lg", _(u"Ganda")),
    ("mk", _(u"Macedonian")),
    ("mh", _(u"Marshallese")),
    ("ml", _(u"Malayalam")),
    ("mi", _(u"Maori")),
    ("mr", _(u"Marathi")),
    ("ms", _(u"Malay")),
    ("mg", _(u"Malagasy")),
    ("mt", _(u"Maltese")),
    ("mn", _(u"Mongolian")),
    ("na", _(u"Nauru")),
#    ("nv", _(u"Navajo; Navaho")),
    ("nv", _(u"Navajo")),
    ("nr", _(u"South Ndebele")),
    ("nd", _(u"North Ndebele")),
    ("ng", _(u"Ndonga")),
    ("ne", _(u"Nepali")),
    ("nn", _(u"Norwegian Nynorsk")),
    ("nb", _(u"Norwegian Bokmål")),
    ("no", _(u"Norwegian")),
#    ("ny", _(u"Chichewa; Nyanja")),
    ("ny", _(u"Nyanja")),
    ("oc", _(u"Occitan")),
    ("oj", _(u"Ojibwa")),
    ("or", _(u"Oriya")),
    ("om", _(u"Oromo")),
#    ("os", _(u"Ossetian; Ossetic")),
    ("os", _(u"Ossetic")),
#    ("pa", _(u"Panjabi; Punjabi")),
    ("pa", _(u"Punjabi")),
    ("pi", _(u"Pali")),
    ("pl", _(u"Polish")),
    ("pt", _(u"Portuguese")),
#    ("ps", _(u"Pushto; Pashto")),
    ("ps", _(u"Pushto")),
    ("qu", _(u"Quechua")),
    ("rm", _(u"Romansh")),
#    ("ro", _(u"Romanian; Moldovan")),
    ("ro", _(u"Romanian")),
    ("rn", _(u"Rundi")),
    ("ru", _(u"Russian")),
    ("sg", _(u"Sango")),
    ("sa", _(u"Sanskrit")),
#    ("si", _(u"Sinhala; Sinhalese")),
    ("si", _(u"Sinhala")),
    ("sk", _(u"Slovak")),
    ("sl", _(u"Slovenian")),
    ("se", _(u"Northern Sami")),
    ("sm", _(u"Samoan")),
    ("sn", _(u"Shona")),
    ("sd", _(u"Sindhi")),
    ("so", _(u"Somali")),
#    ("st", _(u"Sotho; Southern")),
    ("st", _(u"Sotho")),
    ("es", _(u"Spanish")),
    ("sc", _(u"Sardinian")),
    ("sr", _(u"Serbian")),
    ("ss", _(u"Swati")),
    ("su", _(u"Sundanese")),
    ("sw", _(u"Swahili")),
    ("sv", _(u"Swedish")),
    ("ty", _(u"Tahitian")),
    ("ta", _(u"Tamil")),
    ("tt", _(u"Tatar")),
    ("te", _(u"Telugu")),
    ("tg", _(u"Tajik")),
    ("tl", _(u"Tagalog")),
    ("th", _(u"Thai")),
    ("ti", _(u"Tigrinya")),
    ("to", _(u"Tonga")),
    ("tn", _(u"Tswana")),
    ("ts", _(u"Tsonga")),
    ("tk", _(u"Turkmen")),
    ("tr", _(u"Turkish")),
    ("tw", _(u"Twi")),
#    ("ug", _(u"Uighur; Uyghur")),
    ("ug", _(u"Uyghur")),
    ("uk", _(u"Ukrainian")),
    ("ur", _(u"Urdu")),
    ("uz", _(u"Uzbek")),
    ("ve", _(u"Venda")),
    ("vi", _(u"Vietnamese")),
    ("vo", _(u"Volapük")),
    ("wa", _(u"Walloon")),
    ("wo", _(u"Wolof")),
    ("xh", _(u"Xhosa")),
    ("yi", _(u"Yiddish")),
    ("yo", _(u"Yoruba")),
#    ("za", _(u"Zhuang; Chuang")),
    ("za", _(u"Zhuang")),
    ("zu", _(u"Zulu"))
)

dLANG_CHOICES = dict(LANG_CHOICES)

languages = {
    'de': (
        ("ab", u"Abchasisch"),("aa", u"Afar"),("af", u"Afrikaans"),("ak", u"Akan"),("sq", u"Albanisch"),("el", u"Altgriechisch"),("am", u"Amharisch"),("ar", u"Arabisch"),("an", u"Aragonesisch"),("hy", u"Armenisch"),("az", u"Aserbaidschanisch"),("as", u"Assamesisch"),("ae", u"Avestisch"),("av", u"Awarisch"),("ay", u"Aymara"),("bm", u"Bambara"),("ba", u"Baschkirisch"),("eu", u"Baskisch"),("bn", u"Bengalisch"),("dz", u"Bhutanisch"),("bh", u"Biharisch"),("my", u"Birmanisch"),("bi", u"Bislama"),("bs", u"Bosnisch"),("br", u"Bretonisch"),("bg", u"Bulgarisch"),("ch", u"Chamorro"),("zh", u"Chinesisch"),("cr", u"Cree"),("da", u"Dänisch"),("de", u"Deutsch"),("en", u"Englisch"),("eo", u"Esperanto"),("et", u"Estnisch"),("ee", u"Ewe"),("fo", u"Färöisch"),("fj", u"Fidschianisch"),("fi", u"Finnisch"),("fr", u"Französisch"),("fy", u"Friesisch"),("ff", u"Fulfulde"),("gd", u"Gälisch"),("gl", u"Galizisch"),("lg", u"Ganda"),("ka", u"Georgisch"),("kl", u"Grönländisch"),("gn", u"Guarani"),("gu", u"Gujarati"),("ht", u"Haitianisch"),("ha", u"Hausa"),("he", u"Hebräisch"),("hz", u"Herero"),("hi", u"Hindi"),("ho", u"Hiri Motu"),("io", u"Ido"),("ig", u"Igbo"),("id", u"Indonesisch"),("iu", u"Inukitut"),("ik", u"Inupiak"),("ga", u"Irisch"),("is", u"Isländisch"),("it", u"Italienisch"),("ja", u"Japanisch"),("jv", u"Javanisch"),("yi", u"Jiddisch"),("km", u"Kambodschanisch"),("kn", u"Kannada"),("kr", u"Kanuri"),("kk", u"Kasachisch"),("ks", u"Kaschmirisch"),("ca", u"Katalanisch"),("ki", u"Kikuyu"),("ky", u"Kirgisisch"),("kv", u"Komi"),("kg", u"Kongo"),("ko", u"Koreanisch"),("kw", u"Kornisch"),("co", u"Korsisch"),("hr", u"Kroatisch"),("ku", u"Kurdisch"),("kj", u"Kwanyama"),("lo", u"Laotisch"),("la", u"Latein"),("lv", u"Lettisch"),("li", u"Limburgisch"),("ln", u"Lingala"),("lt", u"Litauisch"),("lu", u"Luba-Katanga"),("lb", u"Luxemburgisch"),("mg", u"Malagassy"),("ms", u"Malaiisch"),("ml", u"Malayalam"),("dv", u"Maledivisch"),("mt", u"Maltesisch"),("gv", u"Manx"),("mi", u"Maori"),("mr", u"Marathi"),("mh", u"Marschallesisch"),("mk", u"Mazedonisch"),("mn", u"Mongolisch"),("na", u"Nauruisch"),("nv", u"Navajo"),("ng", u"Ndonga"),("ne", u"Nepalesisch"),("nl", u"Niederländisch"),("nd", u"Nord-Ndebele"),("se", u"Nord-Samisch"),("no", u"Norwegisch"),("nb", u"Norwegisch Bokmål"),("ny", u"Nyanja"),("nn", u"Nynorsk"),("oj", u"Ojibwa"),("oc", u"Okzitanisch"),("or", u"Orija"),("om", u"Oromo"),("os", u"Ossetisch"),("pi", u"Pali"),("pa", u"Pandschabisch"),("ps", u"Paschtu"),("fa", u"Persisch"),("pl", u"Polnisch"),("pt", u"Portugiesisch"),("qu", u"Quechua"),("rw", u"Ruandisch"),("ro", u"Rumänisch"),("rm", u"Rumantsch"),("rn", u"Rundi-Sprache"),("ru", u"Russisch"),("sm", u"Samoanisch"),("sg", u"Sango"),("sa", u"Sanskrit"),("sc", u"Sardisch"),("sv", u"Schwedisch"),("sr", u"Serbisch"),("sn", u"Shona"),("ii", u"Sichuan-Yi"),("sd", u"Sindhi"),("si", u"Singhalesisch"),("sk", u"Slowakisch"),("sl", u"Slowenisch"),("so", u"Somali"),("st", u"Sotho"),("es", u"Spanisch"),("sw", u"Suaheli"),("nr", u"Süd-Ndebele"),("su", u"Sundanesisch"),("ss", u"Swazi"),("tg", u"Tadschikisch"),("tl", u"Tagalog"),("ty", u"Tahitisch"),("ta", u"Tamil"),("tt", u"Tatarisch"),("te", u"Telugu"),("th", u"Thailändisch"),("bo", u"Tibetisch"),("ti", u"Tigrinja"),("to", u"Tongaisch"),("cs", u"Tschechisch"),("ce", u"Tschetschenisch"),("cv", u"Tschuwaschisch"),("ts", u"Tsonga"),("tn", u"Tswana"),("tr", u"Türkisch"),("tk", u"Turkmenisch"),("tw", u"Twi"),("ug", u"Uigurisch"),("uk", u"Ukrainisch"),("hu", u"Ungarisch"),("ur", u"Urdu"),("uz", u"Usbekisch"),("ve", u"Venda"),("vi", u"Vietnamesisch"),("vo", u"Volapük"),("cy", u"Walisisch"),("wa", u"Wallonisch"),("be", u"Weißrussisch"),("wo", u"Wolof"),("xh", u"Xhosa"),("yo", u"Yoruba"),("za", u"Zhuang"),("zu", u"Zulu"),        
        ),
    'en': (
        ("ab", u"Abkhazian"),("aa", u"Afar"),("af", u"Afrikaans"),("ak", u"Akan"),("sq", u"Albanian"),("am", u"Amharic"),("ar", u"Arabic"),("an", u"Aragonese"),("hy", u"Armenian"),("as", u"Assamese"),("av", u"Avaric"),("ae", u"Avestan"),("ay", u"Aymara"),("az", u"Azeri"),("bm", u"Bambara"),("ba", u"Bashkir"),("eu", u"Basque"),("be", u"Belarusian"),("bn", u"Bengali"),("bh", u"Bihari"),("bi", u"Bislama"),("bs", u"Bosnian"),("br", u"Breton"),("bg", u"Bulgarian"),("my", u"Burmese"),("ca", u"Catalan"),("ch", u"Chamorro"),("ce", u"Chechen"),("zh", u"Chinese"),("cv", u"Chuvash"),("kw", u"Cornish"),("co", u"Corsican"),("cr", u"Cree"),("hr", u"Croatian"),("cs", u"Czech"),("da", u"Danish"),("dv", u"Divehi"),("nl", u"Dutch"),("dz", u"Dzongkha"),("en", u"English"),("eo", u"Esperanto"),("et", u"Estonian"),("ee", u"Ewe"),("fo", u"Faroese"),("fj", u"Fijian"),("fi", u"Finnish"),("fr", u"French"),("ff", u"Fulah"),("gd", u"Gaelic"),("gl", u"Galician"),("lg", u"Ganda"),("ka", u"Georgian"),("de", u"German"),("el", u"Greek"),("gn", u"Guarani"),("gu", u"Gujarati"),("ht", u"Haitian"),("ha", u"Hausa"),("he", u"Hebrew"),("hz", u"Herero"),("hi", u"Hindi"),("ho", u"Hiri Motu"),("hu", u"Hungarian"),("is", u"Icelandic"),("io", u"Ido"),("ig", u"Igbo"),("id", u"Indonesian"),("iu", u"Inuktitut"),("ik", u"Inupiaq"),("ga", u"Irish"),("it", u"Italian"),("ja", u"Japanese"),("jv", u"Javanese"),("kl", u"Kalaallisut"),("kn", u"Kannada"),("kr", u"Kanuri"),("ks", u"Kashmiri"),("kk", u"Kazakh"),("km", u"Khmer"),("ki", u"Kikuyu"),("rw", u"Kinyarwanda"),("ky", u"Kirghiz"),("kv", u"Komi"),("kg", u"Kongo"),("ko", u"Korean"),("kj", u"Kuanyama"),("ku", u"Kurdish"),("lo", u"Lao"),("la", u"Latin"),("lv", u"Latvian"),("li", u"Limburgish"),("ln", u"Lingala"),("lt", u"Lithuanian"),("lu", u"Luba-Katanga"),("lb", u"Luxembourgish"),("mk", u"Macedonian"),("mg", u"Malagasy"),("ms", u"Malay"),("ml", u"Malayalam"),("mt", u"Maltese"),("gv", u"Manx"),("mi", u"Maori"),("mr", u"Marathi"),("mh", u"Marshallese"),("mn", u"Mongolian"),("na", u"Nauru"),("nv", u"Navajo"),("ng", u"Ndonga"),("ne", u"Nepali"),("se", u"Northern Sami"),("nd", u"North Ndebele"),("no", u"Norwegian"),("nb", u"Norwegian Bokmål"),("nn", u"Norwegian Nynorsk"),("ny", u"Nyanja"),("oc", u"Occitan"),("oj", u"Ojibwa"),("or", u"Oriya"),("om", u"Oromo"),("os", u"Ossetic"),("pi", u"Pali"),("fa", u"Persian"),("pl", u"Polish"),("pt", u"Portuguese"),("pa", u"Punjabi"),("ps", u"Pushto"),("qu", u"Quechua"),("ro", u"Romanian"),("rm", u"Romansh"),("rn", u"Rundi"),("ru", u"Russian"),("sm", u"Samoan"),("sg", u"Sango"),("sa", u"Sanskrit"),("sc", u"Sardinian"),("sr", u"Serbian"),("sn", u"Shona"),("ii", u"Sichuan-Yi"),("sd", u"Sindhi"),("si", u"Sinhala"),("sk", u"Slovak"),("sl", u"Slovenian"),("so", u"Somali"),("st", u"Sotho"),("nr", u"South Ndebele"),("es", u"Spanish"),("su", u"Sundanese"),("sw", u"Swahili"),("ss", u"Swati"),("sv", u"Swedish"),("tl", u"Tagalog"),("ty", u"Tahitian"),("tg", u"Tajik"),("ta", u"Tamil"),("tt", u"Tatar"),("te", u"Telugu"),("th", u"Thai"),("bo", u"Tibetan"),("ti", u"Tigrinya"),("to", u"Tonga"),("ts", u"Tsonga"),("tn", u"Tswana"),("tr", u"Turkish"),("tk", u"Turkmen"),("tw", u"Twi"),("uk", u"Ukrainian"),("ur", u"Urdu"),("ug", u"Uyghur"),("uz", u"Uzbek"),("ve", u"Venda"),("vi", u"Vietnamese"),("vo", u"Volapük"),("wa", u"Walloon"),("cy", u"Welsh"),("fy", u"Western Frisian"),("wo", u"Wolof"),("xh", u"Xhosa"),("yi", u"Yiddish"),("yo", u"Yoruba"),("za", u"Zhuang"),("zu", u"Zulu"),
        ),
    'es': (
        ("ab", u"abjaso"),("aa", u"afar"),("af", u"afrikaans"),("ay", u"aimara"),("ak", u"akan"),("sq", u"albanés"),("de", u"alemán"),("am", u"amí¡rico"),("ar", u"árabe"),("an", u"aragonés"),("hy", u"armenio"),("as", u"asamés"),("av", u"avar"),("ae", u"avéstico"),("az", u"azerí"),("bm", u"bambara"),("ba", u"bashkir"),("bn", u"bengalí"),("be", u"bielorruso"),("bh", u"bihari"),("my", u"birmano"),("bi", u"bislama"),("nb", u"bokmal noruego"),("bs", u"bosnio"),("br", u"bretón"),("bg", u"búlgaro"),("ks", u"cachemiro"),("km", u"cachemiro"),("kn", u"canarés"),("ca", u"catalán"),("ch", u"chamorro"),("ce", u"checheno"),("cs", u"checo"),("zh", u"chino"),("cv", u"chuvash"),("si", u"cingalés"),("ko", u"coreano"),("kw", u"córnico"),("co", u"corso"),("cr", u"cree"),("hr", u"croata"),("da", u"danés"),("dv", u"divehi"),("dz", u"dzongkha"),("sk", u"eslovaco"),("sl", u"esloveno"),("es", u"español"),("eo", u"esperanto"),("et", u"estonio"),("ee", u"ewe"),("fo", u"feroés"),("fj", u"fidjiano"),("fi", u"finés"),("fr", u"francés"),("fy", u"frisón"),("ff", u"fula"),("gd", u"gaélico"),("gv", u"gaélico manés"),("cy", u"galés"),("gl", u"gallego"),("lg", u"ganda"),("ka", u"georgiano"),("el", u"griego"),("kl", u"groenlandés"),("gn", u"guaraní"),("gu", u"gujarati"),("ht", u"haitiano"),("ha", u"hausa"),("he", u"hebreo"),("hz", u"herero"),("hi", u"hindi"),("ho", u"hiri motu"),("hu", u"húngaro"),("io", u"ido"),("ig", u"igbo"),("id", u"indonesio"),("en", u"inglés"),("iu", u"inuktitut"),("ik", u"inupiaq"),("ga", u"irlandés"),("is", u"islandés"),("it", u"italiano"),("ja", u"japonés"),("jv", u"javanés"),("kr", u"kanuri"),("kk", u"kazajo"),("ki", u"kikuyu"),("rw", u"kinyarwanda"),("ky", u"kirghiz"),("rn", u"kiroundi"),("kv", u"komi"),("kg", u"kongo"),("kj", u"kuanyama"),("ku", u"kurdo"),("lo", u"laosiano"),("la", u"latín"),("lv", u"letón"),("li", u"limburgués"),("ln", u"lingala"),("lt", u"lituano"),("lu", u"luba-katanga"),("lb", u"luxemburgués"),("mk", u"macedonio"),("ml", u"malayalam"),("ms", u"malayo"),("mg", u"malgache"),("mt", u"maltés"),("mi", u"maorí"),("mr", u"marathi"),("mh", u"marshalés"),("mn", u"mongol"),("na", u"nauruano"),("nv", u"navajo"),("nr", u"ndebele meridional"),("nd", u"ndebele septentrional"),("ng", u"ndonga"),("nl", u"neerlandés"),("ne", u"nepalí"),("no", u"noruego"),("ny", u"nyanja"),("nn", u"nynorsk noruego"),("oc", u"occitano"),("oj", u"ojibwa"),("or", u"oriya"),("om", u"oromo"),("os", u"osético"),("pi", u"pali"),("ps", u"pashto"),("fa", u"persa"),("pl", u"polaco"),("pt", u"portugués"),("pa", u"punjabi"),("qu", u"quechua"),("rm", u"retorrománico"),("ro", u"rumano"),("ru", u"ruso"),("se", u"sami septentrional"),("sm", u"samoano"),("sg", u"sango"),("sa", u"sánscrito"),("sc", u"sardo"),("sr", u"serbio"),("st", u"sesotho"),("tn", u"setchwana"),("sn", u"shona"),("ii", u"sichuan-yi"),("sd", u"sindhi"),("ss", u"siswati"),("so", u"somalí"),("sv", u"sueco"),("su", u"sundanés"),("sw", u"swahili"),("tl", u"tagalo"),("ty", u"tahitiano"),("th", u"tailandés"),("ta", u"tamil"),("tt", u"tártaro"),("tg", u"tayico"),("te", u"telugu"),("bo", u"tibetano"),("ti", u"tigriña"),("to", u"tongano"),("ts", u"tsonga"),("tr", u"turco"),("tk", u"turcomano"),("tw", u"twi"),("uk", u"ucraniano"),("ug", u"uigur"),("wo", u"uolof"),("ur", u"urdu"),("uz", u"uzbeko"),("wa", u"valón"),("eu", u"vasco"),("ve", u"venda"),("vi", u"vietnamita"),("vo", u"volapük"),("xh", u"xhosa"),("yi", u"yídish"),("yo", u"yoruba"),("za", u"zhuang"),("zu", u"zulú"),
        ),
    'fr': (
        ("ab", u"abkhaze"),("aa", u"afar"),("af", u"afrikaans"),("ak", u"akan"),("sq", u"albanais"),("de", u"allemand"),("am", u"amharique"),("en", u"anglais"),("ar", u"arabe"),("an", u"aragonais"),("hy", u"arménien"),("ro", u"aroumain"),("as", u"assamais"),("av", u"avar"),("ae", u"avestique"),("ay", u"aymara"),("az", u"azéri"),("ba", u"bachkir"),("bm", u"bambara"),("eu", u"basque"),("bn", u"bengali"),("bi", u"bichelamar"),("be", u"biélorusse"),("bh", u"biharie"),("my", u"birman"),("bs", u"bosniaque"),("br", u"breton"),("bg", u"bulgare"),("ca", u"catalan"),("ch", u"chamorro"),("zh", u"chinois"),("ko", u"coréen"),("kw", u"cornique"),("co", u"corse"),("cr", u"cree"),("hr", u"croate"),("da", u"danois"),("dz", u"dzongkha"),("es", u"espagnol"),("eo", u"espéranto"),("et", u"estonien"),("ee", u"éwé"),("fo", u"féroïen"),("fj", u"fidjien"),("fi", u"finnois"),("fr", u"français"),("fy", u"frison occidental"),("gd", u"gaélique"),("gl", u"galicien"),("cy", u"gallois"),("lg", u"ganda"),("ka", u"géorgien"),("gu", u"goudjarâtî"),("el", u"grec"),("kl", u"groenlandais"),("gn", u"guarani"),("ht", u"haïtien"),("ha", u"haoussa"),("he", u"hébreu"),("hz", u"héréro"),("hi", u"hindi"),("ho", u"hiri motu"),("hu", u"hongrois"),("io", u"ido"),("ig", u"igbo"),("id", u"indonésien"),("iu", u"inuktitut"),("ik", u"inupiaq"),("ga", u"irlandais"),("is", u"islandais"),("it", u"italien"),("ja", u"japonais"),("jv", u"javanais"),("kn", u"kannada"),("kr", u"kanouri"),("ks", u"kâshmîrî"),("km", u"kâshmîrî"),("kk", u"kazakh"),("ki", u"kikuyu"),("ky", u"kirghize"),("kv", u"komi"),("kg", u"kongo"),("kj", u"kuanyama"),("ku", u"kurde"),("qu", u"langue quechua"),("lo", u"lao"),("la", u"latin"),("lv", u"letton"),("li", u"limbourgeois"),("ln", u"lingala"),("lt", u"lituanien"),("lu", u"luba-katanga"),("lb", u"luxembourgeois"),("mk", u"macédonien"),("ms", u"malais"),("ml", u"malayalam"),("dv", u"maldivien"),("mg", u"malgache"),("mt", u"maltais"),("gv", u"manxois"),("mi", u"maori"),("mr", u"marathe"),("mh", u"marshallais"),("mn", u"mongol"),("na", u"nauruan"),("nv", u"navaho"),("nd", u"ndébélé du Nord"),("nr", u"ndébélé du Sud"),("ng", u"ndonga"),("nl", u"néerlandais"),("nn", u"néo-norvégien"),("ne", u"népalais"),("no", u"norvégien"),("nb", u"norvégien bokmål"),("ny", u"nyanja"),("oc", u"occitan"),("oj", u"ojibwé"),("or", u"oriya"),("om", u"oromo"),("os", u"ossète"),("ug", u"ouïgour"),("ur", u"ourdou"),("uz", u"ouzbek"),("ps", u"pachto"),("pi", u"pâli"),("pa", u"pendjabi"),("fa", u"persan"),("ff", u"peul"),("pl", u"polonais"),("pt", u"portugais"),("rm", u"rhéto-roman"),("rn", u"roundi"),("ru", u"russe"),("rw", u"rwanda"),("se", u"sami du Nord"),("sm", u"samoan"),("sg", u"sangho"),("sa", u"sanskrit"),("sc", u"sarde"),("sr", u"serbe"),("sn", u"shona"),("sd", u"sindhî"),("si", u"singhalais"),("sk", u"slovaque"),("sl", u"slovène"),("so", u"somali"),("st", u"sotho"),("su", u"soundanais"),("sv", u"suédois"),("sw", u"swahili"),("ss", u"swati"),("tg", u"tadjik"),("tl", u"tagalog"),("ty", u"tahitien"),("ta", u"tamoul"),("tt", u"tatar"),("cs", u"tchèque"),("ce", u"tchétchène"),("cv", u"tchouvache"),("te", u"télougou"),("th", u"thaï"),("bo", u"tibétain"),("ti", u"tigrigna"),("to", u"tonga"),("ts", u"tsonga"),("tn", u"tswana"),("tr", u"turc de Crimée"),("tk", u"turkmène"),("tw", u"twi"),("uk", u"ukrainien"),("ve", u"venda"),("vi", u"vietnamien"),("vo", u"volapük"),("wa", u"wallon"),("wo", u"wolof"),("xh", u"xhosa"),("yi", u"yiddish"),("ii", u"yi de Sichuan"),("yo", u"yoruba"),("za", u"zhouang"),("zu", u"zoulou"),
        ),
    'it': (
        ("ab", u"abkhazian"),("aa", u"afar"),("af", u"afrikaans"),("ak", u"akan"),("sq", u"albanese"),("am", u"amarico"),("ar", u"arabo"),("an", u"aragonese"),("hy", u"armeno"),("as", u"assamese"),("av", u"avaro"),("ae", u"avestan"),("ay", u"aymara"),("az", u"azerbaigiano"),("bm", u"bambara"),("ba", u"baschiro"),("eu", u"basco"),("bn", u"bengalese"),("be", u"bielorusso"),("bh", u"bihari"),("my", u"birmano"),("bi", u"bislama"),("bs", u"bosniaco"),("br", u"bretone"),("bg", u"bulgaro"),("ca", u"catalano"),("ce", u"ceceno"),("cs", u"ceco"),("ch", u"chamorro"),("cv", u"chuvash"),("tw", u"ci"),("zh", u"cinese"),("ko", u"coreano"),("kw", u"cornico"),("co", u"corso"),("cr", u"cree"),("hr", u"croato"),("ku", u"curdo"),("da", u"danese"),("dv", u"divehi"),("dz", u"dzongkha"),("he", u"ebraico"),("eo", u"esperanto"),("et", u"estone"),("ee", u"ewe"),("fo", u"faroese"),("fj", u"figiano"),("fi", u"finlandese"),("fr", u"francese"),("fy", u"frisone"),("ff", u"fulah"),("gd", u"gaelico"),("gl", u"galiziano"),("cy", u"gallese"),("lg", u"ganda"),("ka", u"georgiano"),("ja", u"giapponese"),("jv", u"giavanese"),("el", u"greco"),("gn", u"guarana"),("gu", u"gujarati"),("ht", u"haitiano"),("ha", u"haussa"),("hz", u"herero"),("hi", u"hindi"),("ho", u"hiri motu"),("io", u"ido"),("ig", u"igbo"),("id", u"indonesiano"),("en", u"inglese"),("iu", u"inuktitut"),("ik", u"inupiak"),("ga", u"irlandese"),("is", u"islandese"),("it", u"italiano"),("kl", u"kalaallisut"),("kn", u"kannada"),("kr", u"kanuri"),("ks", u"kashmiri"),("kk", u"kazako"),("km", u"khmer"),("ki", u"kikuyu"),("rw", u"kinyarwanda"),("ky", u"kirghiso"),("kv", u"komi"),("kg", u"kongo"),("kj", u"kuanyama"),("lo", u"lao"),("la", u"latino"),("lv", u"lettone"),("li", u"limburgese"),("ln", u"lingala"),("rm", u"lingua rhaeto-romance"),("lt", u"lituano"),("lu", u"luba-katanga"),("lb", u"lussemburghese"),("mk", u"macedone"),("ml", u"malayalam"),("ms", u"malese"),("mg", u"malgascio"),("mt", u"maltese"),("gv", u"manx"),("mi", u"maori"),("mr", u"marathi"),("mh", u"marshallese"),("mn", u"mongolo"),("na", u"nauru"),("nv", u"navajo"),("nd", u"ndebele del nord"),("nr", u"ndebele del sud"),("ng", u"ndonga"),("ne", u"nepalese"),("no", u"norvegese"),("nb", u"norvegese bokmal"),("nn", u"norvegese nynorsk"),("ny", u"nyanja"),("oc", u"occitano"),("oj", u"ojibwa"),("nl", u"olandese"),("or", u"oriya"),("om", u"oromo"),("os", u"ossetico"),("pi", u"pali"),("ps", u"pashto"),("fa", u"persiano"),("pl", u"polacco"),("pt", u"portoghese"),("pa", u"punjabi"),("qu", u"quechua"),("ro", u"rumeno"),("rn", u"rundi"),("ru", u"russo"),("se", u"sami del nord"),("sm", u"samoano"),("sg", u"sango"),("sa", u"sanscrito"),("sc", u"sardo"),("sr", u"serbo"),("sn", u"shona"),("ii", u"sichuan-yi"),("sd", u"sindhi"),("si", u"singalese"),("sk", u"slovacco"),("sl", u"sloveno"),("so", u"somalo"),("st", u"sotho"),("es", u"spagnolo"),("su", u"sundanese"),("sv", u"svedese"),("sw", u"swahili"),("ss", u"swati"),("tl", u"tagalog"),("tg", u"tagicco"),("ty", u"taitiano"),("ta", u"tamil"),("tt", u"tatarico"),("de", u"tedesco"),("te", u"telugu"),("th", u"thai"),("bo", u"tibetano"),("ti", u"tigrinya"),("to", u"tonga"),("ts", u"tsonga"),("tn", u"tswana"),("tr", u"turco"),("tk", u"turcomanno"),("uk", u"ucraino"),("ug", u"uigurico"),("hu", u"ungherese"),("ur", u"urdu"),("uz", u"usbeco"),("wa", u"vallone"),("ve", u"venda"),("vi", u"vietnamita"),("vo", u"volapuk"),("wo", u"volof"),("xh", u"xosa"),("yi", u"yiddish"),("yo", u"yoruba"),("za", u"zhuang"),("zu", u"zulu"),
        ),
    'nl': (
        ("ab", u"Abchazisch"),("aa", u"Afar"),("af", u"Afrikaans"),("ak", u"Akan"),("sq", u"Albanees"),("am", u"Amhaars"),("ar", u"Arabisch"),("an", u"Aragonees"),("hy", u"Armeens"),("as", u"Assamees"),("av", u"Avarisch"),("ae", u"Avestisch"),("ay", u"Aymara"),("az", u"Azerbeidzjaans"),("bm", u"Bambara"),("ba", u"Basjkiers"),("eu", u"Baskisch"),("bn", u"Bengalees"),("bh", u"Bihari"),("my", u"Birmees"),("bi", u"Bislama"),("nb", u"Bokmål Noors "),("bs", u"Bosnisch"),("br", u"Bretons"),("bg", u"Bulgaars"),("ca", u"Catalaans"),("ch", u"Chamorro"),("ce", u"Chechen"),("zh", u"Chinees"),("kw", u"Cornish"),("co", u"Corsicaans"),("cr", u"Cree"),("da", u"Deens"),("dv", u"Divehi"),("de", u"Duits"),("dz", u"Dzongkha"),("en", u"Engels"),("eo", u"Esperanto"),("et", u"Estisch"),("ee", u"Ewe"),("fo", u"Faeröers"),("fj", u"Fijisch"),("fi", u"Fins"),("fr", u"Frans"),("ff", u"Fulah"),("gd", u"Gaelisch"),("gl", u"Galicisch"),("lg", u"Ganda"),("ka", u"Georgisch"),("el", u"Grieks"),("gn", u"Guarani"),("gu", u"Gujarati"),("ht", u"Haïtiaans"),("ha", u"Hausa"),("he", u"Hebreeuws"),("hz", u"Herero"),("hi", u"Hindi"),("ho", u"Hiri Motu"),("hu", u"Hongaars"),("io", u"Ido"),("ga", u"Iers"),("ig", u"Igbo"),("is", u"Ijslands"),("id", u"Indonesisch"),("iu", u"Inuktitut"),("ik", u"Inupiaq"),("it", u"Italiaans"),("ja", u"Japans"),("jv", u"Javaans"),("yi", u"Jiddisch"),("kl", u"Kalaallisut"),("kn", u"Kannada"),("kr", u"Kanuri"),("ks", u"Kasjmiri"),("kk", u"Kazachs"),("km", u"Khmer"),("ki", u"Kikuyu"),("rw", u"Kinyarwanda"),("ky", u"Kirgizisch"),("ku", u"Koerdisch"),("kv", u"Komi"),("kg", u"Kongo"),("ko", u"Koreaans"),("hr", u"Kroatisch"),("kj", u"Kuanyama"),("lo", u"Laotiaans"),("la", u"Latijn"),("lv", u"Lets"),("li", u"Limburgs"),("ln", u"Lingala"),("lt", u"Litouws"),("lu", u"Luba-Katanga"),("lb", u"Luxemburgs"),("mk", u"Macedonisch"),("mg", u"Malagasi"),("ml", u"Malayalam"),("ms", u"Maleis"),("mt", u"Maltees"),("gv", u"Manx"),("mi", u"Maori"),("mr", u"Marathi"),("mh", u"Marshallees"),("mn", u"Mongools"),("na", u"Nauru"),("nv", u"Navajo"),("ng", u"Ndonga"),("nl", u"Nederlands"),("ne", u"Nepalees"),("nn", u"Nieuwnoors"),("nd", u"Noord-Ndbele"),("se", u"Noord Samisch"),("no", u"Noors"),("ny", u"Nyanja"),("oc", u"Occitaans"),("ug", u"Oeigoers"),("uk", u"Oekraïens"),("uz", u"Oezbeeks"),("oj", u"Ojibwa"),("or", u"Oriya"),("om", u"Oromo"),("os", u"Ossetisch"),("pi", u"Pali"),("ps", u"Pasjtoe"),("fa", u"Perzisch"),("pl", u"Pools"),("pt", u"Portugees"),("pa", u"Punjabi"),("qu", u"Quechua"),("ro", u"Roemeens"),("rm", u"Rumantsch"),("rn", u"Rundi"),("ru", u"Russisch"),("sm", u"Samoaans"),("sg", u"Sango"),("sa", u"Sanskriet"),("sc", u"Sardinisch"),("sr", u"Servisch"),("sn", u"Shona"),("ii", u"Sichuan-Yi"),("sd", u"Sindhi"),("si", u"Singalees"),("sl", u"Sloveens"),("sk", u"Slowaaks"),("su", u"Soendanees"),("so", u"Somalisch"),("st", u"Sotho"),("es", u"Spaans"),("sw", u"Swahili"),("ss", u"Swazi"),("tg", u"Tadzjieks"),("tl", u"Tagalog"),("ty", u"Tahitisch"),("ta", u"Tamil"),("tt", u"Tataars"),("te", u"Teloegoe"),("th", u"Thai"),("bo", u"Tibetaans"),("ti", u"Tigrinya"),("to", u"Tonga"),("cs", u"Tsjechisch"),("cv", u"Tsjoevasjisch"),("ts", u"Tsonga"),("tn", u"Tswana"),("tk", u"Turkmeens"),("tr", u"Turks"),("tw", u"Twi"),("ur", u"Urdu"),("ve", u"Venda"),("vi", u"Vietnamees"),("vo", u"Volapük"),("wa", u"Waals"),("cy", u"Welsh"),("fy", u"West-Fries"),("be", u"Wit-Russisch"),("wo", u"Wolof"),("xh", u"Xhosa"),("yo", u"Yoruba"),("za", u"Zhuang"),("nr", u"Zuid-Ndbele"),("zu", u"Zulu"),("sv", u"Zweeds"),
        )
    }

def lang_str(lang_field):
    return ", ".join(
        [ unicode(dLANG_CHOICES[x]) for x in lang_field.split(',') if x ]
    )
