BBBB BBBB
BBBB BBBBBBBBBBB
XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXX XX
    XXXXXXXBBBBB BBBBBXXXXXXXXXXXXXXXXXXX XXXX XXXXBBBBBBBBXXXXXXXX
    XXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXX
    XXXXXXX
      XXXX X
        XXXXXXXX XXXX XX
      X
      XXXXXXX XX X
        XXXXXXXXXXX XX
        XXXXXXXXXXXXXX XX
        XXXXXXXXXXXX XXXXX
      X
      XXXXXXXXXXXXX XXXXXXXXX X
        XXXXXXXX XXXX XX
      X
    XXXXXXXX    
  XXXXXXX
  XXXXXX
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXX
          XXX XXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
            BB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
            XXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXX
            BBBBB
            XXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBXX gettext(u'Home') XXXX
            XXXXX
            XXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'articles') XXXX
            XXXXX
            XXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBXX gettext(u'quotes') XXXX
            XXXXX
            XXX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXX
              XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBXX gettext(u'comments') XXXX
            XXXXX
          XXXXX
        XXXXXX
	    XXXXXXXX XXXXXXXXX
      XXXXXX
    XXXXXX

    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
          BBBBB BBBBBBB
          BBBBBBBB
        XXXXXX
      XXXXXX
    XXXXXX
    
    XXXX XXXXXXXXXXXXXXXXXX
      XXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXX
          XXXXX
          XX XXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXX XXXX XXXXXXXXX
        XXXXXX
      XXXXXX
    XXXXXX
    BBBBB BBBBBBBBBBBBBBBB
  XXXXXXX
XXXXXXX
