BBBBBBB BBBBBBBBBBB
BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXBBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXX
XXXXXX
XXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXX XXXXXXXXXXX  
    XXXXXXXXX
      FFFFFFFFFF
    XXXXXXXXXX
  XXXXXX
XXXXXX

XXXX XXXXXXXXXXXX
  XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX  
    XXXX XXXXXXXXXXXXXXXXXXXX
  XXXXXX
XXXXXX
BBBBBBBB BBBBBBB

BBBBB BBBBBBBB
XXXXXXXX
  XXXXXXXXXXXXXXXXXXXXX X BBBBBBBBBBBBBBBBBBBB BBB BBBBBBX
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX X X
    XXXXXXXXXXXXXXX BB BBBBBBBBBBBBBBBBBBBBBXXXXBBBBXXXXXBBBBBX
    XXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXXX XXXXX
    XXXXXXXXXXXXXX XXXXX
  XX
XXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
BBBBBBBB
