BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXX XXXXXXXXXXXXXXXXXXXX gettext(u'List of articles') XXXXX
XXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  BB BBBBBBBBBBB
  XXXX
    BBB BBBBBBB BB BBBBBBBBBBB
    BBBBBBBBBBBBBBBBB BBB BBBBBBB BB BBBBBBBBBBBBB
    XXXX
      XX XXXXXXXXXXXX
      XXXXX XXXXXXXXXXXXXXFFFFFFFFFFFFXXXXXXX
      BB BBBBBBBBBBBBB
      XXXXX XXXXXXXXXXXXXXX  XXXXXXXFFFFFFFFFXXXXXXX
      BBBBB
    XXXXX
    BBBBBB
  XXXXX
  BBBBB
XXXXXX
BBBBBBBB
