BBBBBBB BBBBBBBBBBB
BBBB BBBB BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBB
XXX XXXXXXXXXXXXXXXXXXXX gettext(u'List of quotes') XXXXX
XXXXX

XXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX
  BB BBBBBBBBBBB
  XXXX
    BBB BBBBB BB BBBBBBBBBBB
    BBBBBBBBBBBBBBBBB BBB BBBBB BB BBBBBBBBBBBBB
    XXXX
      XX XXXXXXXXXXXX
      XXXXXX
      XXXXX XXXXXXXXXXXXXXXX XXXXXXX
      BB BBBBBBBBBBBBB
      XXXXX XXXXXXXXXXXXXXX  XXXXXXXFFFFFFFFFXXXXXXX
      BBBBB
    XXXXX
    BBBBBB
  XXXXX
  BBBBB
XXXXXX
BBBBBBBB
  
