# Generated by Django 4.0.6 on 2022-07-08 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20170523_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='UUIDDiary',
            fields=[
                ('diary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='tests.diary')),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
            ],
            bases=('tests.diary',),
        ),
    ]
