# Generated by Django 5.2.4 on 2025-07-10 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0003_uuiddiary"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "slug",
                    models.SlugField(unique_for_date="publish", verbose_name="slug"),
                ),
                ("quote", models.TextField(verbose_name="quote")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "publish",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="publish"
                    ),
                ),
            ],
            options={
                "db_table": "demo_quotes",
                "ordering": ("-publish",),
            },
        ),
    ]
