# Generated by Django 5.2.5 on 2026-05-12 14:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0004_quote"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiaryWithMTL1",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tests.diary",),
        ),
    ]
