# Generated by Django 3.1.7 on 2021-04-08 06:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique_for_date='published_time', verbose_name='slug')),
                ('body', models.TextField(verbose_name='body')),
                ('allow_comments', models.BooleanField(default=True)),
                ('published_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ('published_time',),
            },
        ),
    ]
