# Generated by Django 5.2.3 on 2025-07-22 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleCommentsL0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "articles w/comments MTL-0",
                "db_table": "articles_comments_l0",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleCommentsL1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "articles w/comments MTL-1",
                "db_table": "articles_comments_l1",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleCommentsL2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "articles w/comments MTL-2",
                "db_table": "articles_comments_l2",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ArticleCommentsL3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "articles w/comments MTL-3",
                "db_table": "articles_comments_l3",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoryCommentsL0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories w/comments MTL-0",
                "db_table": "stories_comments_l0",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoryCommentsL1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories w/comments MTL-1",
                "db_table": "stories_comments_l1",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoryCommentsL2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories w/comments MTL-2",
                "db_table": "stories_comments_l2",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StoryCommentsL3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stories w/comments MTL-3",
                "db_table": "stories_comments_l3",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaleCommentsL0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tales w/comments MTL-0",
                "db_table": "tales_comments_l0",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaleCommentsL1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tales w/comments MTL-1",
                "db_table": "tales_comments_l1",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaleCommentsL2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tales w/comments MTL-2",
                "db_table": "tales_comments_l2",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TaleCommentsL3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
                ("body", models.TextField(verbose_name="body")),
                (
                    "allow_comments",
                    models.BooleanField(default=True, verbose_name="allow comments"),
                ),
                (
                    "published_time",
                    models.DateTimeField(
                        default=datetime.datetime.now, verbose_name="published time"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "tales w/comments MTL-3",
                "db_table": "tales_comments_l3",
                "ordering": ("-published_time",),
                "abstract": False,
            },
        ),
    ]
