# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0002_blacklisteddomain'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xtdcomment',
            options={'ordering': ('-thread_id', 'order')},
        ),
    ]
