# Generated by Django 3.0.1 on 2020-09-20 18:37
from django.db import migrations


#
# This migration has been modified to do nothing. As reported in issue 271,
# running the management command initialize_nested_count as part of this
# migration may try to access the user model when it has not been built in
# the DB yet. So the user model in the DB would not be the same as in the
# code module causing an error.
# https://github.com/danirus/django-comments-xtd/issues/271
#
# The fix consist of keeping this migration but making it non-effective.
#

def noop(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments_xtd', '0007_xtdcomment_nested_count'),
    ]

    operations = [
        migrations.RunPython(noop, reverse_code=migrations.RunPython.noop)
    ]
