# Generated by Django 3.0.1 on 2020-10-14 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_comments_xtd', '0008_auto_20200920_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.IntegerField(choices=[(1, 'I liked it'), (2, 'I disliked it')], db_index=True, verbose_name='reaction')),
                ('counter', models.IntegerField(default=0)),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='django_comments_xtd.XtdComment', verbose_name='reactions')),
            ],
        ),
    ]
