# Generated by Django 5.2.5 on 2025-08-29 13:15

import django.db.models.deletion
import django_comments_xtd.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_comments_xtd", "0008_auto_20200920_2037"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentThread",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(db_index=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="xtdcomment",
            name="thread_id",
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction",
                    django_comments_xtd.models.ReactionField(
                        db_index=True, verbose_name="reaction"
                    ),
                ),
                ("counter", models.IntegerField(default=0)),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="django_comments_xtd.xtdcomment",
                        verbose_name="reactions",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment reactions",
                "verbose_name_plural": "comments reactions",
            },
        ),
        migrations.CreateModel(
            name="CommentReactionAuthor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_comments_xtd.commentreaction",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="commentreaction",
            name="authors",
            field=models.ManyToManyField(
                through="django_comments_xtd.CommentReactionAuthor",
                through_fields=("reaction", "author"),
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="xtdcomment",
            name="thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="django_comments_xtd.commentthread",
            ),
        ),
        migrations.CreateModel(
            name="CommentVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[("+", "+"), ("-", "-")], db_index=True, max_length=1
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="django_comments_xtd.xtdcomment",
                    ),
                ),
            ],
            options={
                "verbose_name": "comment votes",
                "verbose_name_plural": "comments votes",
            },
        ),
    ]
