# Generated by Django 3.2.11 on 2022-01-11 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_comments_xtd.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_comments_xtd', '0008_auto_20200920_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', django_comments_xtd.models.ReactionField(db_index=True, verbose_name='reaction')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='blacklisteddomain',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CommentReactionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_comments_xtd.commentreaction')),
            ],
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='authors',
            field=models.ManyToManyField(through='django_comments_xtd.CommentReactionAuthor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='django_comments_xtd.xtdcomment', verbose_name='reactions'),
        ),
    ]
