BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBBB

BBBBBBBBBBBBBBBBBBBBBBB BB BBBBBBBBB
BBBBBBBBBBBBBBBBBBBB BB BBBBBBBBBBBBBBBB

XXXXXXXXX XXXXX
XXXXXX
  XXXXXX
    XXXXX XXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBX XX
    XXXXXXXBBBBB BBBBBXXXXXXXXBBBBBBBBXXXXXXXX
    XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBXX
    XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBXX

    BBBBB BBBBBBBBBBBBBBBBB
  XXXXXXX
  XXXXXX
    XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXX
          XXXXXX XXXXXXBBB BBBBBBBBBBXXXXXXXXX XXXXXXXXXXXXXXXX
          XXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXX
        XXXX XXXXXXXXXXXXX
          BB BBBBBBBBBBBBBBBBBBBBB
            BB BBBBBBBBBBBBB
              XX XXXXXXBBB BBBBBBBBBBBBBXXXXXXXXXXX
            BBBBB
            XX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXX
          BBBB
            XX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBX XXXXXXBBB BBBBBBBXXXXXXXXXXX
          BBBBB
          XX XXXXXXXBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBX XXXXXXBBB BBBBBBBBBXXXXXXXXXXXXX
          BB BBBBBBBBB BB BBBBBBBBBBBBBBBBBBBBBBB
            XXXXX XXXXXXXXXXXXX XXXXXXX
              BBBBBBBBBBXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XX
            XXXXXXX
            XXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
              XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
                BBB BBBBBBBB BB BBBBBBBBB
                  BBBBBBBBBB BBBBBBBBBBBBBBBB BBBBBBBBBB
                    XXXXXXX XXXXXXXXXFFFFFFFFFFFFFFXXXXXXXXX
                  BBBB
                    XXXXXXX XXXXXXXX XXXXXXXXXFFFFFFFFFFFFFXXXXXXXXX
                  BBBBBBBBBBBBB
                BBBBBB
              XXXXXXXXX
            XXXXXX
          BBBBB
        XXXXXX
      XXXXXX
    XXXXXXXXX

    BBBBB BBBBBBB
    BBBBBBBB

    XXXXXXXX
      XXXX XXXXXXXXXXXXXXXXXX
        XXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX gettext(u'documentation') XXXX
          XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
          XXXXXXXXXXXXXXXXXX
          XX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXX
    XXXXXXXXX

    XXXXXXX XXXXXBBB BBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBXXXXXXXXXXX
    XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBXXXXXXXXXXX

    BBBBB BBBBBBBBBBBBBBBB
  XXXXXXX
XXXXXXX