BBBBBBB BBBBBBBBBBB

BBBB BBBB
BBBB BBBBBB

BBBBB BBBBBBB
XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXX XXX XXXXXXX
      XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXX XXX XXXXXXX XXX XXX XXXXXXXX XX XXXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXX XXX XXXXXX XXXXXXX XXX XXXXXXX XXXXXXXXXXXX XXX XXXXXXX XXXX XXXXXXXXXXX XXXXX XXX XXXX XXXXXXXX XXX XXX XXXX XXX XXXXX XX XXXXXXXX XXXXXXX XXXXXXXXX XXXX XXXX XXXXXXXXXX XX XXXXXXXX XXXXXXX XXXXXXXXX XX XXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX
        XXX
          XXXXXXXX XXX XX XXXXXXX XXX XXXXXXX XXXXXX XXXXX XX XXXXXXXXXXXX XXX XXX XXXXX XXXX XXX XXXXXXXXXX XXX XXXX XXXXXXXXX XXXXX
        XXXX
      XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXX XXX XXXXXXXXXXXXXXX
        XXX
          XXXXXXXXX XXXXXXX XXX XXXXXXX XXXXXXXXXXXXX XX XXXXXXXXX XXXXXXXXX XXXXXXXXXXXXX XXX XX XXXXXXXXX XX XXXXXXXX XX XXX XXXXXXXXXX
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXX
  XXXX XXXXXXXXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX
        XXX
          XXXXXXX XXXXXXXXXXXX XXX XXXXX XXXX XXXXXXXXX XXXXXXX XXX XXX XXXXXXXXXXXXXX XXXXXXXX XXX XXX XXXXXXXX XXXX XXXX XXX XXXXXXXXXX
        XXXX
      XXXXXXXXXX
      XXXXXXXX XXXXXXXXXXXXXXX
        XXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX
        XXX
          XXXXXXXX XXXX XXXX XXX XXXXXXX XXXXXXXXXX XXXX XXX XX XXXXXXXX XX XXX XXX XX XXXXXXXXX XX XXXX XXX XXXXXXXX XX XXXX XXXXXXXX
        XXXX
      XXXXXXXXXX
    XXXXXX
  XXXXXX
XXXXXXX
BBBBBBBB