BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBB

BBBB BBBB
BBBB BBBBBB
BBBB BBBBBBBBBBBB

BBBBB BBBBBXXXXXXXXXXXXXXXXXXXXXXXXXBBBBBBBB

BBBBB BBBBBBBBB
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX
BBBBBBBB

BBBBB BBBBBBBBBBBBBBBBBXXXXXXBBBBBBBB

BBBBB BBBBBBBBBBB
XXXX XXXXXXXXXXXXXXXX XXXXXX
  XXXX XXXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXX
      XXXX gettext(u'Your comments to this website') XXXXX
      BB BBBBBBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXXX XXX XXXXXXXXX XXXXXXXXXXXXXX
      BBBB
      XXX XXXXXXXXXXXXXXXXXXXXXXX XXXX XXX XXXX XXXXXXXX XXXXXXXXX
      BBBBB
      BBB BBBBBBB BB BBBBBBBB
        XXXX XXXXXXXXXXXXX
           gettext(u'Posted to:')  XX XXXXXXXXXXXXX
          BB BBBBBBBBBBBBB B B
            XXXXXX gettext(u'In response to another comment.') 
          BBBBB
          BB BBBBBBBBBBBBBBBBBBBB
            XXXXXX ngettext(u'It has one response.', u'It has %(number_of_responses)s responses.', count) SS SSS SSS SSSSSSSSSPP PPP PPPPPPPPPPPPPPPPPPPPPPP PPPPPPPPPP
          BBBBB
        XXXXXX
        XXXX XXXXXXXBBBBBBBBBBBBBBBBBBB XXXXXX
          XXXX XXXXXXXXXXXXXXXXXX XXXX XXXXXXX
            XXXX XXXXXXXXXXXXXXXX
              XXXX XXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXX XXXXXXBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBXXXXXXXXXXXXX
              XXXXXX
              XXXX XXXXXXXXXXXXXFFFFFFFFFFFFFFFFXXXXXX
              XXXX XXXXXXXXXXXXXXXXXXXXX
            XXXXXX
          XXXXXX
          BB BBBBBBBBBBBBBBBBBBBBBBB B B
            XXX XXXXXXXXXX XXX XXXXXXX
              BBB BBBBBBBB BB BBBBBBBBBBBBBBBBBBBBB
                BBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB
                  XXX XXXXXXXXXXXX
                     ngettext(u'\n                    One person reacted with <span class="emoji">&%(r_icon)s</span>\n                    ', u'\n                    %(r_counter)s people reacted with <span class="emoji">&%(r_icon)s</span>\n                    ', count) 
                    SSS SSSSSS SSSSSSS SSSS SSSSS SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
                    
                    PPPPPPPPPPPPP PPPPPP PPPPPPP PPPP PPPPP PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP
                    
                    XFFFFFFFFFFFFFFFFFFF FX
                  XXXXX
                BBBBBBB
              BBBBBB
            XXXXX
          BBBBB
        XXXXXX
      BBBBBB
    XXXXXX
  XXXXXX
XXXXXX
BBBBBBBB BBBBBBBBBBB